[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools', 'gcc']

[phases.install]
cmds = ['python3.11 -m venv --copies /opt/venv', '. /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.start]
cmd = 'python main_fix.py'